# Generated by Django 5.0.3 on 2024-04-26 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pethostel', '0003_employeereg_is_active_alter_employeereg_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeereg',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=8),
        ),
    ]
