# Generated by Django 5.0.3 on 2024-04-26 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pethostel', '0005_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Normal', 'Normal'), ('Standard', 'Standard'), ('Premium', 'Premium')], max_length=10)),
                ('capacity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('total_rooms', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='petregistration',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=8),
        ),
        migrations.AlterField(
            model_name='petregistration',
            name='weight',
            field=models.FloatField(),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField()),
                ('number_of_pets', models.IntegerField()),
                ('cost', models.IntegerField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pethostel.room')),
            ],
        ),
    ]
