# Generated by Django 5.0.3 on 2024-04-27 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pethostel', '0006_room_alter_petregistration_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='room',
        ),
        migrations.AddField(
            model_name='booking',
            name='room_category',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Standard', 'Standard'), ('Premium', 'Premium')], default='Normal', max_length=10),
        ),
    ]
