# Generated by Django 5.0.3 on 2024-04-27 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pethostel', '0007_remove_booking_room_booking_room_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='id',
        ),
        migrations.AlterField(
            model_name='room',
            name='category',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Standard', 'Standard'), ('Premium', 'Premium')], max_length=10, primary_key=True, serialize=False),
        ),
    ]
