# Generated by Django 5.0.3 on 2024-04-27 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pethostel', '0009_booking_owner_id_booking_pets'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='owner_id',
            new_name='customer',
        ),
    ]
